name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Workflow Environment
        run: |
          echo "github.event_name=${{ github.event_name }}"
          echo "github.ref=${{ github.ref }}"

      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        with:
          submodules: true
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: 10.28.1

      - name: Install Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 24.8.0
          cache: pnpm

      - name: Cache node modules
        uses: actions/cache@v4.3.0
        with:
          path: ./node_modules
          key: app-node-modules-${{ hashFiles('./pnpm-lock.yaml') }}
          restore-keys: |
            app-node-modules-

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Create local tag
        if: ${{ github.event_name == 'push' }}
        uses: actions/github-script@v8.0.0
        with:
          script: |
            const { tsImport } = await import(
              '${{ github.workspace }}/node_modules/tsx/dist/esm/api/index.cjs'
            );
            const { default: createNewVersionTag } = await tsImport(
              './scripts/createNewVersionTag.ts',
              '${{ github.workspace }}/'
            );
            await createNewVersionTag();

      - name: Build
        run: pnpm verify

      - name: Upload
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        id: upload
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: dist/

      - name: Push tag
        if: ${{ github.event_name == 'push' }}
        uses: actions/github-script@v8.0.0
        with:
          github-token: ${{ github.token }}
          script: |
            const { tsImport } = await import(
              '${{ github.workspace }}/node_modules/tsx/dist/esm/api/index.cjs'
            );
            const { default: pushLatestTags } = await tsImport(
              './scripts/pushLatestTags.ts',
              '${{ github.workspace }}/'
            );
            await pushLatestTags(github, context);

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: verify
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4.0.5
